recipes-kernel: Remove to fix build
Error was:

Exception: bb.fetch2.MalformedUrl: The URL: '${LINUX_GIT_URI}/${LINUX_GIT_PREFIX}${LINUX_GIT_REPO};branch=${LINUX_GIT_BRANCH};protocol=${LINUX_GIT_PROTOCOL}' is invalid and cannot be interpreted